title: Dr Jason M Rampelt - Academic Activities
description: Research and Publications
url: "https://jmrampelt.github.io"
baseurl: "/my-portfolio-site" 

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark # Use 'auto' to automatically match the visitor's device settings


plugins:
  - jekyll-remote-theme
